#!/bin/sh
# exifautotran [list of files]
#
# Transforms Exif files so that Orientation becomes 1
#

trap "if test -n \"\$tempfile\"; then rm -f \"\$tempfile\"; fi" INT QUIT TERM

for i
do
 case $i in
 -v|--version) echo "exifautotran"; exit 0;;
 -h|--help) 
             cat <<EOF
exifautotran [list of files]

Transforms Exif files so that Orientation becomes 1
EOF
             exit 0;;
 esac

 case `jpegexiforient -n "$i"` in
 1) transform="";;
 2) transform="-flip horizontal";;
 3) transform="-rotate 180";;
 4) transform="-flip vertical";;
 5) transform="-transpose";;
 6) transform="-rotate 90";;
 7) transform="-transverse";;
 8) transform="-rotate 270";;
 *) transform="";;
 esac
 if test -n "$transform"; then
  tempfile=`mktemp`;
  if test "$?" -ne "0"; then
    echo "Failed to create temporary file" >&2
    exit 1;
  fi
  echo Executing: jpegtran -copy all $transform $i >&2
  jpegtran -copy all $transform "$i" > $tempfile
  if test $? -ne 0; then
   echo Error while transforming $i - skipped. >&2
   rm "$tempfile"
  else
   cp "$tempfile" "$i"
   rm "$tempfile"
   jpegexiforient -1 "$i" > /dev/null
  fi
 fi
done
