.TH EXIFAUTOTRAN "1" "February 2005" "exifautotran" "User Commands"
.SH NAME
exifautotran \- Transforms Exif files so that Orientation becomes 1
.SH DESCRIPTION
exifautotran [list of files]
.PP
Take a list of files as input and transform them in place so that the
Orientation becomes 1.
.SH "AUTHOR"
    Guido Vollbeding <guido@jpegclub.org>
.SH "SEE ALSO"
.BR jpegtran(1)
.BR jpegexiforient(1)
